project_name: syno-vm

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: syno-vm
    binary: syno-vm
    main: ./cmd/syno-vm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: syno-vm
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: scttfrdmn
    name: syno-vm
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto

brews:
  - name: syno-vm
    repository:
      owner: scttfrdmn
      name: homebrew-syno-vm
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/scttfrdmn/syno-vm
    description: "A command-line tool for managing Synology Virtual Machine Manager"
    license: MIT
    test: |
      system "#{bin}/syno-vm --version"
    install: |-
      bin.install "syno-vm"

dockers:
  - image_templates:
      - "ghcr.io/scttfrdmn/syno-vm:{{ .Tag }}"
      - "ghcr.io/scttfrdmn/syno-vm:v{{ .Major }}"
      - "ghcr.io/scttfrdmn/syno-vm:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/scttfrdmn/syno-vm:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    use: buildx
    goos: linux
    goarch: amd64