name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        run: |
          echo "Formula updated by GoReleaser from syno-vm repository"
          echo "Version: ${{ github.event.client_payload.version }}"
          echo "URL: ${{ github.event.client_payload.url }}"